---
stages:
  - test
  - build

test-job:
  stage: test
  image: "rust:latest"
  script:
    - cargo test
  only:
    - tags

build-job:
  stage: build
  image: "rust:latest"
  script:
    - cargo install cargo-deb
    - cargo build --release
    - cargo deb
    - ls target/debian/monit-agregator_0.1.0_amd64.deb
  artifacts:
    paths:
      - target/release/monit-agregator
      - target/debian/monit-agregator_0.1.0_amd64.deb
  only:
    - tags
