---
stages:
  - build
  - release

build:
  stage: build
  image: "rust:latest"
  before_script:
    # need build id to link assets
    - echo BUILD_JOB_ID=$CI_JOB_ID >> build.env
  script:
    - cargo test
    - cargo install cargo-deb
    - cargo build --release
    - cargo deb
  artifacts:
    paths:
      - target/release/${CI_PROJECT_NAME}
      - target/debian/${CI_PROJECT_NAME}_0.1.0_amd64.deb
    reports:
      dotenv: build.end
  rules:
    - if: $CI_COMMIT_TAG

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "running release_job, BUILD_JOB_ID=${BUILD_JOB_ID}"
  needs:
    - job: build
      artifacts: true
  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
  # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  # https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html#create-a-release-when-a-git-tag-is-created
  # https://crypt.codemancers.com/posts/2021-08-31-release-artifacts-using-gitlab-cicd/
  release:
    name: 'Release Executables $CI_COMMIT_SHORT_SHA'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    assets:
      links:
        - name: 'Linux amd64'
          url: 'https://gitlab.com/${CI_PROJECT_PATH}/-/jobs/${BUILD_JOB_ID}/artifacts/file/target/release/${CI_PROJECT_NAME}'
        - name: 'Debian package amd64'
          url: 'https://gitlab.com/${CI_PROJECT_PATH}/-/jobs/${BUILD_JOB_ID}/artifacts/file/target/debian/${CI_PROJECT_NAME}_${CI_COMMIT_TAG}_amd64.deb'
  rules:
    - if: $CI_COMMIT_TAG
