---
ip: "0.0.0.0"
port: 3030
wait_period: 60
hosts:
  - name: "host1"
    url: "http://192.168.0.1:28"
    public_url: "https://monit.domain.com/host1/"
  - name: "host2"
    url: "http://192.168.0.2:28"
    public_url: "https://monit.domain.com/host2/"
