---
ip: "0.0.0.0"
port: 3030
wait_period: 60      # refresh period for hosts status
hosts:
  - name: "host1"                                  # name displayed in webui
    url: "http://192.168.0.1:28"                   # url the binary access
    public_url: "https://monit.domain.com/host1/"  # optional
  - name: "host2"
    url: "http://192.168.0.2:28"
